<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1 on 2022-08-16 02:32
=======
# Generated by Django 4.1 on 2022-08-15 19:15
=======
<<<<<<< HEAD
# Generated by Django 4.1 on 2022-08-15 12:21
=======
# Generated by Django 4.1 on 2022-08-15 14:49
>>>>>>> yeonseo0814
=======
# Generated by Django 4.1 on 2022-08-14 03:35
>>>>>>> sookyung_eunseo
>>>>>>> dongheon0814

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('year', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=20, null=True)),
=======
>>>>>>> dongheon0814
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
<<<<<<< HEAD
=======
                ('profile_img', models.TextField()),
>>>>>>> dongheon0814
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.birthdaypage')),
            ],
        ),
    ]
