# Generated by Django 4.1 on 2022-08-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypage',
            name='selected_cake',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
