# Generated by Django 4.1 on 2022-08-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_receiver_post_sender_birthdaypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='posts.birthdaypage'),
        ),
    ]
