# Generated by Django 4.1 on 2022-08-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_birthdaypage_selected_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaypage',
            name='selected_cake',
        ),
    ]
