# Generated by Django 3.2.15 on 2022-08-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='desc',
            new_name='temp',
        ),
    ]
