# Generated by Django 4.1 on 2022-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_cake',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
