# Generated by Django 4.1 on 2022-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmies', '0002_alter_tmimessage_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmimessage',
            name='like_state',
            field=models.BooleanField(default=False, verbose_name='게시글좋아요'),
        ),
    ]
